[versions]
# libraries
junit = "4.13.2"
kotlinSerialization = "1.8.1"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.2"
compilerSerialization = "2.2.0"
spotless = "7.0.3"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization"}
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "compilerSerialization" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
